// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3tcolRgTTw2S9CoVzZcUEYq5QohQP7qY',
    appId: '1:1014654012011:android:593bdec37e96c866debf2e',
    messagingSenderId: '1014654012011',
    projectId: 'carsapp-5413c',
    databaseURL: 'https://carsapp-5413c-default-rtdb.firebaseio.com',
    storageBucket: 'carsapp-5413c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMB-ys3MANE58fdUZn2n5Sqte8kKuAYZw',
    appId: '1:1014654012011:ios:d189bd82afc01c06debf2e',
    messagingSenderId: '1014654012011',
    projectId: 'carsapp-5413c',
    databaseURL: 'https://carsapp-5413c-default-rtdb.firebaseio.com',
    storageBucket: 'carsapp-5413c.appspot.com',
    iosBundleId: 'com.example.amaliyotVazifa',
  );
}
